version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - node -v
      - npm -v
      - npm install

  build:
    commands:
      - echo Build phase...
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'
